services:
  magic_pinecone:
    build:
      context: .
      dockerfile: Dockerfile
    image: magic-pinecone-backend-light:latest
    container_name: magic_pinecone_backend
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    volumes:
      - .:/app
      - app_venv:/app/.venv
    expose:
      - "8000"
    networks:
      - public_net
      - db_net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  db:
    image: postgres:17-alpine
    container_name: magic_pinecone_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:5.4.2
    container_name: magic_pinecone_adminer
    expose:
      - "8080"
    networks:
      - public_net
      - db_net
    depends_on:
      - db

  caddy:
    image: caddy:2.9.1-alpine
    container_name: magic_pinecone_caddy
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8081:8081"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - public_net
    depends_on:
      - magic_pinecone
      - adminer

networks:
  public_net:
    driver: bridge
  db_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  app_venv:
    driver: local
