"""initial_migration

Revision ID: a0a053e842e9
Revises: 
Create Date: 2026-05-29 15:40:51.043988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a053e842e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_category'), 'scholarships', ['category'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_course_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scholarship_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chinese_name', sa.String(), nullable=True),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('study_system', sa.String(), nullable=True),
    sa.Column('student_status', sa.String(), nullable=True),
    sa.Column('employee_type', sa.String(), nullable=True),
    sa.Column('employee_status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_table('departments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('college_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['college_name'], ['colleges.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('class_no', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('password_card', sa.String(), nullable=True),
    sa.Column('teachers', sa.Text(), nullable=True),
    sa.Column('class_times', sa.Text(), nullable=True),
    sa.Column('limit_cnt', sa.Integer(), nullable=True),
    sa.Column('admit_cnt', sa.Integer(), nullable=True),
    sa.Column('wait_cnt', sa.Integer(), nullable=True),
    sa.Column('college_name', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('course_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['college_name'], ['colleges.name'], ),
    sa.ForeignKeyConstraint(['department_name'], ['departments.name'], ),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_courses_class_no'), 'courses', ['class_no'], unique=False)
    op.create_index(op.f('ix_courses_serial_no'), 'courses', ['serial_no'], unique=False)
    op.create_table('course_details',
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('books', sa.Text(), nullable=True),
    sa.Column('teaching_method', sa.Text(), nullable=True),
    sa.Column('grading_policy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['serial_no'], ['courses.serial_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_course_details_serial_no'), 'course_details', ['serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_details_serial_no'), table_name='course_details')
    op.drop_table('course_details')
    op.drop_index(op.f('ix_courses_serial_no'), table_name='courses')
    op.drop_index(op.f('ix_courses_class_no'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_scholarships_category'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
